development:
  adapter: postgresql
  encoding: unicode
  database: micro-learning
  pool: 2
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>

test:
  adapter: postgresql
  encoding: unicode
  database: tests
  pool: 2
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>